# version: '3.8'

services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app 

  app:
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - "3000:5000"